export const AGREGAR_EMPRESA = 'AGREGAR_EMPRESA';
export const AGREGAR_EMPRESA_EXITO = 'AGREGAR_EMPRESA_EXITO';
export const AGREGAR_EMPRESA_ERROR = 'AGREGAR_EMPRESA_ERROR';

export const OBTENER_EMPRESAS = 'OBTENER_EMPRESAS';
export const OBTENER_EMPRESAS_EXITO = 'OBTENER_EMPRESAS_EXITO';
export const OBTENER_EMPRESAS_ERROR = 'OBTENER_EMPRESAS_ERROR';

export const OBTENER_EMPRESA_ELIMINAR = 'OBTENER_EMPRESA_ELIMINAR';
export const OBTENER_EMPRESA_ELIMINAR_EXITO = 'OBTENER_EMPRESA_ELIMINAR_EXITO';
export const OBTENER_EMPRESA_ELIMINAR_ERROR = 'OBTENER_EMPRESA_ELIMINAR_ERROR';

export const OBTENER_EMPRESA_EDITAR = 'OBTENER_EMPRESA_EDITAR';
export const COMENZAR_EDICION_EMPRESA = 'COMENZAR_EDICION_EMPRESA';
export const OBTENER_EMPRESA_EDITAR_EXITO = 'OBTENER_EMPRESA_EDITAR_EXITO';
export const OBTENER_EMPRESA_EDITAR_ERROR = 'OBTENER_EMPRESA_EDITAR_ERROR';

//Noticias Types
export const AGREGAR_NOTICIA = 'AGREGAR_NOTICIA';
export const AGREGAR_NOTICIA_EXITO = 'AGREGAR_NOTICIA_EXITO';
export const AGREGAR_NOTICIA_ERROR = 'AGREGAR_NOTICIA_ERROR';

export const OBTENER_NOTICIAS = 'OBTENER_NOTICIAS';
export const OBTENER_NOTICIAS_EXITO = 'OBTENER_NOTICIAS_EXITO';
export const OBTENER_NOTICIAS_ERROR = 'OBTENER_NOTICIAS_ERROR';

export const OBTENER_NOTICIA_ELIMINAR = 'OBTENER_NOTICIA_ELIMINAR';
export const OBTENER_NOTICIA_ELIMINAR_EXITO = 'OBTENER_NOTICIA_ELIMINAR_EXITO';
export const OBTENER_NOTICIA_ELIMINAR_ERROR = 'OBTENER_NOTICIA_ELIMINAR_ERROR';

export const OBTENER_NOTICIA_EDITAR = "OBTENER_NOTICIA_EDITAR";
export const COMENZAR_EDICION_NOTICIA = "COMENZAR_EDICION_NOTICIA";


//Noticias Asociadas
export const OBTENER_NOTICIAS_ASOCIADAS = 'OBTENER_NOTICIAS_ASOCIADAS';
export const OBTENER_NOTICIAS_ASOCIADAS_EXITO = 'OBTENER_NOTICIAS_ASOCIADAS_EXITO';
export const OBTENER_NOTICIAS_ASOCIADAS_ERROR = 'OBTENER_NOTICIAS_ASOCIADAS_ERROR';





